# Generated by Django 5.1.7 on 2025-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationphase',
            name='phase_type',
            field=models.CharField(choices=[('baseline', 'Baseline Evaluation'), ('midline', 'Midline Evaluation'), ('endline', 'Endline Evaluation'), ('inception', 'Inception'), ('design', 'Design'), ('data_collection', 'Data Collection'), ('analysis', 'Analysis'), ('reporting', 'Reporting'), ('dissemination', 'Dissemination')], max_length=20),
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('projects', models.ManyToManyField(blank=True, related_name='evaluators', to='research_dashboard.researchproject')),
            ],
        ),
    ]
