# Generated by Django 5.1.7 on 2025-03-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dashboard', '0002_alter_evaluationphase_phase_type_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='completed',
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
