# Generated by Django 5.1.7 on 2025-04-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dashboard', '0004_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='powerbi_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='PowerBI Dashboard URL'),
        ),
    ]
