# Generated by Django 5.1.7 on 2025-06-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dashboard', '0007_role_evaluator_roles_userprofile_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationphase',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
    ]
