# Generated by Django 5.1.7 on 2025-06-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_dashboard', '0008_evaluationphase_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationphase',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
