name: Deploy to CyberPanel Server

# This action will only trigger on a push to the "main" branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v3

    # Step 2: SSH into the server and run the deployment script
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Exit immediately if a command exits with a non-zero status.
          set -e
          
          # Navigate to the project directory
          cd /home/researcheval.ac.ke/public_html/
          
          # Pull the latest changes from the main branch
          git pull origin main
          
          # Activate the virtual environment
          source venv/bin/activate
          
          # Install dependencies
          pip install -r requirements.txt
          
          # Run migrations
          python manage.py migrate
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Restart OpenLiteSpeed to apply changes
          /usr/local/lsws/bin/lswsctrl restart